### PR TITLE
fix: backport style_parser fixes

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit backport style parser fixes from https://github.com/angular/angular/pull/49460

### CODE REVIEW

**Comment by alan-agius4** [comment]
Please wait until https://github.com/angular/angular/pull/49460 is merged before merging this.

**Comment by alan-agius4** [comment]
Green CI run in angular/angular with these changes
https://app.circleci.com/pipelines/github/angular/angular/57806/workflows/ed454830-439c-465e-bafb-6080af82636e/jobs/1303971

**Review by AndrewKushnir — APPROVED** [review]

**Comment by AndrewKushnir** [comment]
cc @jessicajaniuk

**Comment by AndrewKushnir** [comment]
Just for documentation purposes: we are waiting for https://github.com/angular/angular/pull/49460 to land. Once it lands, this PR can be merged as well.

**Comment by alan-agius4** [comment]
https://github.com/angular/angular/pull/49460 has been merged

**Pull request merged**
